export const MESSAGE_SENT = 'message sent';
export const JOIN_ROOM = 'join room';
export const GAME_START = 'game start';
export const UPDATE_PLAYERS = 'update players';
export const UPDATE_TABLE = 'update table';
export const CHECK = 'check';
export const CALL = 'call';
export const BET = 'bet';
export const FOLD = 'fold';
